services:
  # Your Web Service (Website)
  - type: web
    name: gdg-vit-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18


